target-version = "py310"

lint.select = ["ALL"]

lint.ignore = [
  "COM812",  # missing-trailing-comma, incompatible with the Ruff formatter
  "CPY001",  # flake8-copyright, missing-copyright-notice
  "D107",  # undocumented-public-init, unnecessary if the class has a docstring
  "D203",  # one-blank-line-before-class, incompatible with D211
  "D213",  # multi-line-summary-second-line, incompatible with D212
]
