name: Lint

on:
  push:
  pull_request:
  schedule:
    - cron: 0 0 1 * *  # monthly

permissions:
  contents: read

jobs:
  gitlint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Create requirements.txt
        run: echo 'gitlint' >requirements.txt

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'
          cache: pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run gitlint
        run: gitlint

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Run pre-commit
        uses: tox-dev/action-pre-commit-uv@v1
